version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - python -m pip install --no-deps -e .

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt