preprocessing:
  adapters:
    - name: pano_adapter
      params:
        top_cut_frac: 0.0
        max_size: 384
    - name: intent_identity_adapter
    - name: future_states_identity_adapter
    - name: past_states_identity_adapter
    - name: preference_trajectory_adapter
    - name: detections_3d_identity_adapter
    - name: lidar_adapter
    - name: hdmap_bev_adapter
      params:
        min_x: -32.0
        max_x: 32.0
        min_y: -32.0
        max_y: 32.0
        pixels_per_meter: 4.0
        polyline_thickness: 1
dataset:
  features:
    - frame_name: current_sensors
      modalities:
        - cameras
        - intent
        - past_states
        - lidar_pc
        - hd_map_bev
      selector:
        name: current
  labels:
    - frame_name: current_future_states
      modalities:
        - future_states
        - preference_trajectory
      selector:
        name: current
